=== torkjel/upside/src/main/resources/upside-conf.dtd
<?xml encoding="UTF-8"?>

<!-- The upside element defines the configuration of an Upside instance.

    base-url    - the base url of the update sites served by this Upside
                  instance. The servlet container running the Upside instance
                  must be separately configured to expose Upside on this url.
                  E.g "http://mysite.example.com/"
-->
<!ELEMENT upside (site+, federated-site+)>
<!ATTLIST upside
    base-url        CDATA #REQUIRED
>

<!-- The site element lists an external update site from which features can be
     included in a federated site.

    name    - name of the site. This is used by Include tags to refer to a
              site.
    url     - the url to a site. This must point to the base directory of
              the site. E.g. "http://foo.bar/update-site/"
-->
<!ELEMENT site EMPTY>
<!ATTLIST site
    name            CDATA #REQUIRED
    url             CDATA #REQUIRED
>

<!-- The federated-site defines a "virtual" update site, composed of features
     from one or more external update sites. These are the update sites which
     are served by Upside.

    name    - the name of the federated site. This is used to construct the
              site's url. The url of the federated site will be a combination
              of this name and the base-url. E.g: If name is "updates", the
              full url of the site will be "http://mysite.example.com/updates".
-->
<!ELEMENT federated-site (description?, (category | include)+)>
<!ATTLIST federated-site
    name            CDATA #REQUIRED
>

<!-- A textual description of a federated site or a category in a federated
     site.
-->
<!ELEMENT description (#PCDATA)>

<!-- The category element defines a category of features in a federated site.

    name    - the name of the category. This will be the name and label shown
              in the Eclipse update manager.
-->
<!ELEMENT category (description?, include+)>
<!ATTLIST category
    name            CDATA #REQUIRED
>

<!-- The include element specifies a set of features to include in a
     federated site. These features can be included directly in a site, or in
     the category of a site. The element comes in three varieties
     1: if only site is defined it will match all features in the specified
        external site
     2: if site and category is defined it will match all features in the
        given category of the external site
     3: if site and feature (an optionally version) is defined it will match
        that specific feature of the external site. The version attribute can
        be used to restrict matching to a specific version of the feature, if
        there are several. TODO: specify version wildcards...

    site            - the name of an external site
    category        - the name of a category in the external site
    feature         - the name of a category in the external site
    version         - the version of a feature in the external site.
    keep-categories - when including a feature from an external site, all the
                      categories that feature is a member of can also be
                      included automatically by setting this to "true". Note
                      that this does not cause other features in those
                      categories to be included.
-->
<!ELEMENT include EMPTY>
<!ATTLIST include
    site            CDATA #REQUIRED
    category        CDATA #IMPLIED
    feature         CDATA #IMPLIED
    version         CDATA #IMPLIED
    keep-categories CDATA "false"
>

=== torkjel/upside/src/test/resources/test-conf.xml
<?xml version="1.1" encoding="UTF-8"?>
<!--
 Copyright 2010 Torkjel Hongve (torkjelh@conduct.no)

 This file is part of Upside.

 Upside is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Upside is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Upside.  If not, see <http://www.gnu.org/licenses/>.
-->
<!DOCTYPE upside SYSTEM "upside-conf.dtd">

<upside base-url="http://upside.example.com/">

  <site name="foo" url="http://foo.example.com/site/"/>
  <site name="bar" url="http://bar.example.com/update-site/"/>

  <federated-site name="main">
    <description>Main site</description>

    <category name="cat-foo">
      <description>Foo stuff</description>
      <include site="foo"/>
      <include site="foo" category="zooc"/>
      <include site="foo" feature="zoof"/>
      <include site="foo" feature="zoofv" version="2.0"/>
    </category>

    <category name="cat-bar">
      <include site="bar"/>
    </category>

    <include site="foo" keep-categories="true"/>
    <include site="bar" category="barc"/>
    <include site="foo" feature="foo" version="1.0"/>

  </federated-site>

  <federated-site name="test">
    <category name="test">
        <description>Test category</description>
        <include site="foo"/>
    </category>
  </federated-site>

</upside>

=== torkjel/upside/src/test/resources/merge-config.xml
<?xml version="1.1" encoding="UTF-8"?>
<!--
 Copyright 2010 Torkjel Hongve (torkjelh@conduct.no)

 This file is part of Upside.

 Upside is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Upside is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Upside.  If not, see <http://www.gnu.org/licenses/>.
-->
<!DOCTYPE upside SYSTEM "upside-conf.dtd">

<upside base-url="http://upside.example.com/">

  <site name="site1" url="http://foo/site1"/>
  <site name="site2" url="http://foo/site2"/>

  <federated-site name="merged">
    <description>Merged site</description>

    <include site="site1" keep-categories="true"/>

    <include site="site2"/>

    <category name="lion">
        <include site="site1" category="mouse"/>
        <include site="site2" feature="feature2b" keep-categories="true"/>
    </category>

  </federated-site>

</upside>
